name: Recreate Release from Existing Artifacts

on:
  workflow_dispatch:

jobs:
  recreate-release:
    runs-on: ubuntu-latest
    steps:
      - name: Download previous artifacts
        uses: dawidd6/action-download-artifact@v2
        with:
          name: "addon-*"
          branch: builder  # 你的构建分支
          workflow: builder.yml  # 原构建 workflow 文件名
          path: artifacts
          
      - name: Rename corrupted CUDA files
        shell: bash
        run: |
          # 根据实际错误文件名编写重命名逻辑
          # 示例：假设 CUDA 文件名错误为 addon-.node
          find artifacts -name "addon-.node" | while read -r file; do
            parent_dir=$(basename $(dirname "$file"))
            cuda_version=$(echo "$parent_dir" | cut -d'-' -f2)
            build_type=$(echo "$parent_dir" | cut -d'-' -f3)
            new_name="addon-windows-cuda-${cuda_version}-${build_type}.node"
            mv "$file" "artifacts/$new_name"
          done

      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: latest
          name: "Fixed whisper.cpp builds"
          files: |
            artifacts/*.node
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
